spring.application.name=campusconnect

spring.datasource.url=jdbc:mysql://localhost:3306/campus_connect
spring.datasource.username=root
spring.datasource.password=Harini@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
